### ISSUE TITLE
Node not pruning correctly when running in a Docker container?

### ISSUE THREAD

**Issue by MatthewDarnell** [OpenEthereum/open-ethereum#11383]
- **Parity Ethereum version**: 2.5.13
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I have a 250GB SSD, 32 GB of RAM. I am trying to get the node running and pruning so that I won't run out of space. I seem to keep running out of memory for some reason. I have some ws connections querying the node for transactions.

Here is my docker-compose file:

```
version: '2'

services:
  parity:
    image: parity/parity:v2.5.13-stable
    restart: always
    command: >
               --pruning fast
               --pruning-memory 200000
               --warp-barrier 
               --base-path /root/.parity
               --no-jsonrpc
               --db-compaction ssd
               --cache-size 4096
               --min-peers 50
               --max-peers 200
               --ws-interface all
               --ws-origins 127.0.0.1
    ports:
      - "8546:8546"
      - "30303:30303"
    user: root
    volumes:
      - /mnt/ethereum:/root/.parity:rw
volumes:
  ethereum-data:
```

It seemed to be synced up last night, and I saw the chain was around 52GB, but this morning I looked at it and it had run out of space.

```
parity_1  | 2020-01-15 03:48:14 UTC Imported #9283352 0xfc7c…6d45 (95 txs, 5.78 Mgas, 804 ms, 17.07 KiB)
parity_1  | 2020-01-15 03:48:44 UTC   #5464650   33/50 peers      1 GiB chain    2 GiB db  0 bytes queue  280 MiB sync  RPC:  3 conn,   23 req/s,  815 µs
parity_1  | memory allocation of 2449473552 bytes failed
ethereum_parity_1 exited with code 137
```

And when I check the chain data:

```
$ df -h /mnt/ethereum/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda        248G  247G     0 100% /mnt/ethereum
```

What is going on? Shouldn't a warp barrier of `8500000` and pruning-memory set to 200GB be working?

**Comment by dvdplm** [comment]
> pruning-memory set to 200GB be working?

Pruning memory is an alternative way limiting the amount of memory used to keep ancient state in RAM. It does not have any effect on the disk space used.

```
   --pruning-memory=[MB]
        The ideal amount of memory in megabytes to use to store recent states. As many states as possible will be kept
        within this limit, and at least --pruning-history states will always be kept. (default: 32)
```

My advice would be to remove the `--pruning-memory` setting and run with the default (32Mb) for a while and see if that setting works for you. If you want to keep a longer history than the default 64 blocks most users prefer using the `--pruning-history` setting.

**Comment by MatthewDarnell** [comment]
> Pruning memory is an alternative way limiting the amount of memory used to keep ancient state in RAM. It does not have any effect on the disk space used.


Thanks, for some reason I read that as disk as opposed to in memory. Will try that and see if it is any better.
