### ISSUE TITLE
Lite wallet is not returning correct transaction data within new blocks

### ISSUE THREAD

**Issue by MatthewDarnell** [OpenEthereum/open-ethereum#11519]
- **Parity Ethereum version**: 2.5.13
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**: no 

I am running parity in a docker container with the following settings:

```services:
  parity:
    image: parity/parity:v2.5.13-stable
    restart: always
    command: >
               --pruning fast
               --light
               --warp-barrier 9465000
               --base-path /root/.parity
               --no-jsonrpc
               --db-compaction ssd
               --cache-size 4096
               --min-peers 50
               --max-peers 200
               --ws-interface all
               --ws-origins 127.0.0.1
...
```

I am connecting to the node via `ws` in javascript with the `Web3js` library. Everything works fine, I'm able to query blocks including transactions and it works well.

However, since I switched to a light node, I have noticed something strange. Sometimes, when I scan a block, it doesn't retrieve all the transactions included in that block. 

I.e.: 
```
let nextBlock = await web3.eth.block.getBlock(lastBlockScanned + 1, true)
if (nextBlock !== null) {
  logger.info(`Finished scanning ${nextBlock.number}. ${nextBlock.transactions.length} txs.`)
}
```

Again, this has always been working fine. However, I've occasionally gotten some bad results, such as:

`Finished scanning 9554437. 115 txs.`

If you check etherscan, you'll see that this block actually contains `186` transactions, NOT `115`.

I reset `lastBlockScanned` to `9554430` and let it loop back up, then I saw this:

`Finished scanning 9554437. 186 txs.` <-- which is correct

Why is it occasionally returning different results for the same block? Is it somehow possible that if I query a block too soon after it's mined, this lite wallet will return bogus results? As in, before the lite wallet can download the headers or something? It has done this multiple times now, and each time I rescan it later, it returns the correct transactions.

**Comment by emilbayes** [comment]
This block was forked. Perhaps you are scanning too close to the head of the chain?

https://etherscan.io/block/9554437/f
https://etherscan.io/block/9554437

**Comment by MatthewDarnell** [comment]
You are right. I was scanning the head and when I rescan it, it's fine. I have added a delay. Thank you.
