### ISSUE TITLE
Parity CLI exits with error during startup

### ISSUE THREAD

**Issue by jmazan** [OpenEthereum/open-ethereum#11517]
- **Parity Ethereum version**: Parity-Ethereum/v2.7.2-stable-d961010f63-20200205/x86_64-pc-windows-msvc
- **Operating system**: Windows 10 Pro
- **Installation**: precompiled binary
- **Fully synchronized**: no
- **Network**: Volta.json
- **Restarted**: no

After running the following command (either under cygwin or windows cmd):
parity.exe --chain Volta.json

I got the following error on the console:

> 2020-02-25 08:30:03  Starting Parity-Ethereum/v2.7.2-stable-d961010f63-20200205/x86_64-pc-windows-msvc/rustc1.41.0
> 2020-02-25 08:30:03  Keys path C:\Users\HP\AppData\Roaming\Parity\Ethereum\keys\Volta
> 2020-02-25 08:30:03  DB path C:\Users\HP\AppData\Local\Parity\Ethereum\chains\Volta\db\d94a0a739a3e416a
> 2020-02-25 08:30:03  State DB configuration: fast
> 2020-02-25 08:30:03  Operating mode: active

> ====================

> stack backtrace:
>   0:     0x7ff67450ea66 - <no info>
>   1:     0x7ff674ec389d - <no info>
>   2:     0x7ff674ec36b1 - <no info>
>   3:     0x7ff675bae3bb - <no info>
>   4:     0x7ff675bb5398 - <no info>
>   5:     0x7ff6745d4c3d - <no info>
>   6:     0x7ff6745db90f - <no info>
>   7:     0x7ff674d68185 - <no info>
>   8:     0x7ff674c6a84e - <no info>
>   9:     0x7ff674c2e5e8 - <no info>
>  10:     0x7ff675bcf077 - <no info>
>  11:     0x7ff675bd1e5c - <no info>
>  12:     0x7ffc5ed67bd4 - BaseThreadInitThunk

>Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: >BadDER }', src\libcore\result.rs:1188

**Comment by niklasad1** [comment]
Duplicated, closing in favor of #11515
