### ISSUE TITLE
[Rinkeby/Mainnet] eth_call data returns OutOfGas VM execution error

### ISSUE THREAD

**Issue by davidalbela** [OpenEthereum/open-ethereum#11541]
Parity Ethereum version: 2.7.2
    Operating system: GNU/Linux
    Installation: Docker
    Fully synchronized: yes
    Network: Rinkeby, Mainnet
    Restarted: yes

Some `eth_call` to read the method `getUsersPaginated` in contract address [0xc576ea7bd102f7e476368a5e98fa455d1ea34de2](https://rinkeby.etherscan.io/address/0xc576ea7bd102f7e476368a5e98fa455d1ea34de2#readContract) fails: 
```
curl -H "Content-Type: application/json" -X POST http://localhost:8545 -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x95466a460000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e8","to":"0xc576ea7bd102f7e476368a5e98fa455d1ea34de2"},"latest"],"id":1}'
```

with the following error:
```
{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Out of gas"},"id":1}
```

~~Same kind of requests are returning the expected output in **Parity mainnet**~~. In mainnet network Parity is responding sometimes with the same error message:
```
curl -H "Content-Type: application/json" -X POST http://localhost:8546 -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x95466a46000000000000000000000000eb13c6ff42f1307c026a7f6e2c97068658d9aea6000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000003e8","to":"0x6f400810b62df8e13fded51be75ff5393eaa841f"},"latest"],"id":70457}'

{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Out of gas"},"id":70457}
```

In **Geth** nodes both networks (rinkeby and mainnet) are responding fine with the expected result.

**Request:** Discover where and why Parity is replying with these `eth_call` errors and fix it.

**Comment by niklasad1** [comment]
@davidalbela 

The call always fails on `ropsten` and sometimes on `mainet`?

**Comment by davidalbela** [comment]
> The call always fails on `ropsten` and sometimes on `mainet`?

Until now I only got the error on `rinkeby`. But with this sample same error is happening on `mainnet`:

**Comment by niklasad1** [comment]
Ok, is your node synced with `tracing`?

Then it could be useful if you could run [trace_call](https://wiki.parity.io/JSONRPC-trace-module#trace_call) instead of `eth_call`, to understand what's going on.

I'm surprised by this `eth_call` shouldn't consume any gas

**Comment by davidalbela** [comment]
Sorry, finally I see that was something with the use of the amount of gas in  `eth_call` requests, decreasing the `pageSize` value the requests are working fine. Thanks for your help @niklasad1
